export const ICONS = {
  // Execution Flow Icons
  START: '🚀',
  END: '✅',
  PROCESSING: '⚙️',
  COMPLETED: '🎯',
  CANCELLED: '🚫',
  TIMEOUT: '⏰',
  PAUSED: '⏸️',
  RESUMED: '▶️',
  STOPPED: '⏹️',
  RESTART: '🔄',
  INITIALIZE: '🔧',
  FINALIZE: '🏁',

  // Data Flow Icons
  ARGS: '📥',
  RESPONSE: '📤',
  INPUT: '📝',
  OUTPUT: '📄',
  DATA: '💾',
  CACHE: '🗄️',
  STREAM: '🌊',
  BUFFER: '📦',
  QUEUE_DATA: '📋',
  REDIRECT: '↪️',
  FORWARD: '➡️',
  BACKWARD: '⬅️',
  PAYLOAD: '📨',
  EVENT: '📣',
  MESSAGE_BUS: '🚌',
  WEBHOOK: '🪝',
  TOPIC: '📰',

  // Log Level Icons
  INFO: 'ℹ️',
  DEBUG: '🐛',
  WARN: '⚠️',
  ERROR: '❌',
  FATAL: '💀',
  SUCCESS: '✅',
  VERBOSE: '🔍',
  NOTICE: '📢',
  CRITICAL: '🚨',
  EMERGENCY: '🚨',

  // Method & Function Icons
  METHOD: '🔧',
  FUNCTION: '⚡',
  CALLBACK: '🔄',
  ASYNC: '⏳',
  PROMISE: '🤝',
  GENERATOR: '🔄',
  ITERATOR: '📋',
  MIDDLEWARE: '🔗',
  INTERCEPTOR: '🎯',
  GUARD: '🛡️',
  FILTER: '🔍',
  HANDLER: '🎛️',
  CONTROLLER: '🕹️',

  // Database Icons
  DB_QUERY: '🔍',
  DB_INSERT: '➕',
  DB_UPDATE: '✏️',
  DB_DELETE: '🗑️',
  DB_CONNECT: '🔗',
  DB_DISCONNECT: '🔌',
  DB_TRANSACTION: '💳',
  DB_MIGRATION: '📦',
  DB_BACKUP: '💾',
  DB_RESTORE: '📥',
  DB_INDEX: '📊',
  DB_OPTIMIZE: '⚡',
  DATABASE: '🗃️',
  POSTGRESQL: '🐘',
  MYSQL: '🐬',
  MARIADB: '🦭',
  MONGODB: '🍃',
  REDIS: '🔴',
  ELASTICSEARCH: '🔎',
  CLICKHOUSE: '🏠',
  SQLITE: '💽',
  DYNAMODB: '📘',
  FIRESTORE: '🔥',

  // Network Icons
  HTTP_REQUEST: '🌐',
  HTTP_RESPONSE: '📡',
  API_CALL: '📞',
  WEBSOCKET: '🔌',
  GRPC: '🔧',
  REST_API: '🌍',
  GRAPHQL: '📊',
  SOAP: '🧼',
  MICROSERVICE: '🔗',
  LOAD_BALANCER: '⚖️',
  PROXY: '🔄',
  GATEWAY: '🚪',
  HTTP_REDIRECT: '↪️',
  HTTP_WARN: '⚠️',
  HTTP_ERROR: '❌',
  HTTP_INFO: 'ℹ️',
  HTTP_DEBUG: '🐛',
  HTTP_SUCCESS: '✅',
  HTTP_VERBOSE: '🔍',
  HTTP_NOTICE: '📢',
  HTTP_CRITICAL: '🚨',
  HTTP_EMERGENCY: '🚨',
  DNS: '🌐',
  CDN: '🛰️',
  INGRESS: '🚪',
  EGRESS: '🏃',

  // File Operations Icons
  FILE_READ: '📖',
  FILE_WRITE: '✍️',
  FILE_DELETE: '🗑️',
  FILE_UPLOAD: '📤',
  FILE_DOWNLOAD: '📥',
  FILE_COPY: '📋',
  FILE_MOVE: '📁',
  FILE_COMPRESS: '🗜️',
  FILE_EXTRACT: '📦',
  FILE_ENCRYPT: '🔒',
  FILE_DECRYPT: '🔓',
  FILE_SCAN: '🔍',

  // Authentication & Security Icons
  AUTH: '🔐',
  LOGIN: '🔑',
  LOGOUT: '🚪',
  PERMISSION: '🛡️',
  TOKEN: '🎫',
  JWT: '🎫',
  OAUTH: '🔗',
  SSO: '🔐',
  MFA: '🔢',
  PASSWORD: '🔒',
  ENCRYPTION: '🔐',
  DECRYPTION: '🔓',
  HASH: '🔢',

  // Queue & Job Icons
  QUEUE: '📋',
  JOB_START: '🏁',
  JOB_COMPLETE: '🏆',
  JOB_FAIL: '💥',
  RETRY: '🔄',
  JOB_PENDING: '⏳',
  JOB_RUNNING: '🏃',
  JOB_CANCELLED: '🚫',
  JOB_TIMEOUT: '⏰',
  JOB_PRIORITY: '⭐',
  JOB_SCHEDULE: '📅',
  BULLMQ: '🐂',
  REDIS_QUEUE: '🔴',
  RABBITMQ: '🐰',
  KAFKA: '📨',
  NATS: '✉️',
  SQS: '📬',
  SNS: '📣',
  PUBSUB: '📡',
  CRON: '⏱️',

  // Monitoring & Tracing Icons
  TRACE: '🔍',
  SPAN: '📏',
  METRIC: '📊',
  ALERT: '🚨',
  HEALTH: '💚',
  SENTRY: '🛡️',
  PROMETHEUS: '📈',
  GRAFANA: '📊',
  JAEGER: '🔍',
  ZIPKIN: '📏',
  LOGGING: '📝',
  MONITORING: '👁️',
  TELEMETRY: '📡',
  OBSERVABILITY: '🧭',

  // External Services Icons
  EMAIL: '📧',
  SMS: '📱',
  PUSH_NOTIFICATION: '🔔',
  PAYMENT: '💳',
  STORAGE: '☁️',
  AWS: '☁️',
  AZURE: '🔵',
  GCP: '🔴',
  DOCKER: '🐳',
  KUBERNETES: '⚓',
  TELEGRAM: '📱',
  SLACK: '💬',
  DISCORD: '🎮',
  TWITTER: '🐦',
  FACEBOOK: '📘',
  GOOGLE: '🔍',
  GITHUB: '🐙',
  OPENAI: '🧠',
  STRIPE: '💳',
  PAYPAL: '💰',
  SENDGRID: '✉️',
  TWILIO: '📞',
  CLOUDFLARE: '☁️',
  VERCEL: '▲',
  NETLIFY: '⬢',
  FIREBASE: '🔥',
  SUPABASE: '⚡',
  POSTMAN: '📮',
  VAULT: '🔐',
  NGINX: '🟩',
  TERRAFORM: '🟪',
  HELM: '⎈',
  ARGOCD: '🌀',

  // System Icons
  CONFIG: '⚙️',
  ENV: '🌍',
  MEMORY: '🧠',
  CPU: '⚡',
  DISK: '💿',
  NETWORK: '🌐',
  PROCESS: '⚙️',
  THREAD: '🧵',
  GARBAGE_COLLECTION: '🗑️',
  UPTIME: '⏱️',
  DOWNTIME: '⏸️',
  BACKUP: '💾',
  RESTORE: '📥',
  MAINTENANCE: '🔧',
  RUNTIME: '🏃',
  WORKER: '👷',
  SCHEDULER: '🗓️',
  CONTAINER: '📦',
  POD: '🫛',
  NODE: '🧱',
  CLUSTER: '🕸️',
  SECRETS: '🗝️',
  FEATURE_FLAG: '🚩',
  SERVICE_MESH: '🕸️',
  OBJECT_STORAGE: '🪣',
  SEARCH: '🔎',
  EVENT_STREAM: '🌊',
  MESSAGE_QUEUE: '📬',
  ETL: '🔄',
  CDC: '🧬',

  // Business Logic Icons
  USER: '👤',
  ADMIN: '🧑‍💼',
  OPERATOR: '🧑‍🔧',
  BROWSER: '🌐',
  WEB_APP: '🖥️',
  MOBILE_APP: '📱',
  CLI_APP: '⌨️',
  BATCH_JOB: '🗓️',
  TEST_RUNNER: '🧪',
  ORDER: '📦',
  PRODUCT: '🛍️',
  TRANSACTION: '💰',
  REPORT: '📈',
  CUSTOMER: '👥',
  INVENTORY: '📦',
  SHIPPING: '🚚',
  BILLING: '💳',
  ANALYTICS: '📊',
  DASHBOARD: '📋',
  SETTINGS: '⚙️',
  PROFILE: '👤',
  ACCOUNT: '🏦',
  SUBSCRIPTION: '📅',
  CHECKOUT: '🛒',
  CART: '🛒',

  // Validation Icons
  VALIDATE: '✅',
  INVALID: '❌',
  REQUIRED: '🔴',
  OPTIONAL: '🟡',
  SCHEMA: '📋',
  TYPE_CHECK: '🔍',
  SANITIZE: '🧹',
  ESCAPE: '🚪',
  ENCODE: '🔢',
  DECODE: '🔓',
  ESCALATE: '📈',

  // Performance Icons
  SLOW: '🐌',
  FAST: '⚡',
  OPTIMIZE: '🚀',
  BOTTLENECK: '🍾',
  LATENCY: '⏱️',
  THROUGHPUT: '📊',
  MEMORY_LEAK: '💧',
  CPU_INTENSIVE: '🔥',
  I_O_INTENSIVE: '💾',
  NETWORK_LATENCY: '🌐',
  CACHE_HIT: '🎯',
  CACHE_MISS: '❌',

  // Error Handling Icons
  EXCEPTION: '💥',
  STACK_TRACE: '📚',
  RECOVERY: '🔄',
  FALLBACK: '🛟',
  TIMEOUT_ERROR: '⏰',
  NETWORK_ERROR: '🌐',
  VALIDATION_ERROR: '❌',
  AUTH_ERROR: '🔐',
  RATE_LIMIT: '🚦',
  CIRCUIT_BREAKER: '⚡',
  DEADLOCK: '🔒',
  RACE_CONDITION: '🏁',

  // Testing Icons
  TEST: '🧪',
  MOCK: '🎭',
  STUB: '🪵',
  ASSERT: '🎯',
  UNIT_TEST: '🧪',
  INTEGRATION_TEST: '🔗',
  E2E_TEST: '🌐',
  PERFORMANCE_TEST: '⚡',
  LOAD_TEST: '📊',
  STRESS_TEST: '🔥',
  COVERAGE: '📊',
  CI_CD: '🔄',

  // Development Icons
  HOT_RELOAD: '🔥',
  BUILD: '🔨',
  DEPLOY: '🚀',
  VERSION: '🏷️',
  GIT: '📝',
  MERGE: '🔀',
  BRANCH: '🌿',
  COMMIT: '💾',
  PUSH: '📤',
  PULL: '📥',
  CODE_REVIEW: '👀',
  REFACTOR: '🔧',
  PROFILING: '📊',

  // Architecture / Diagram Icons
  ARCHITECTURE: '🏗️',
  DESIGN: '🎨',
  DOCUMENTATION: '📚',
  TUTORIAL: '📖',
  EXAMPLE: '💡',
  TEMPLATE: '📋',
  SAMPLE: '🔬',
  MESSAGE: '📝',
  CORE: '⬡',
  PORT: '🔌',
  ADAPTER: '🧩',
  DRIVER: '🕹️',
  DRIVEN: '🧲',
  DOMAIN: '🏛️',
  CONTRACT: '📜',
  POLICY: '📏',
  BOUNDARY: '🧱',
  SERVICE: '🧰',
  REPOSITORY: '🗂️',
  ACTOR: '🧍',
  FLOW: '🧭',
  SEQUENCE: '🪜',
  SWITCHBOARD: '🎛️',
  APPLICATION: '🧠',
  USE_CASE: '🎬',
  ENTITY: '🧱',
  VALUE_OBJECT: '🔹',
  AGGREGATE: '🧩',
  DOMAIN_EVENT: '📣',
  COMMAND: '🪄',
  QUERY: '🔍',
  DTO: '📄',
  MAPPER: '🗺️',
  FACADE: '🏛️',
  ORCHESTRATOR: '🎼',
  PIPELINE: '🪜',
  CHECKPOINT: '📍',
  LANE: '🛣️',

  // Miscellaneous Icons
  UNKNOWN: '❓',
  DEPRECATED: '⚠️',
  EXPERIMENTAL: '🧪',
  BETA: 'β',
  ALPHA: 'α',
  LEGACY: '📜',
  FUTURE: '🔮',
  INNOVATION: '💡',
  TREND: '📈',
  PATTERN: '🎨',
} as const;

export type IconName = keyof typeof ICONS;
