name: CI
    on:
      push:
        branches: [ main ]
      pull_request:
        branches: [ main ]
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Set up Go
          uses: actions/setup-go@v3
          with:
            go-version: '1.22'
        - name: Run go fmt
          run: go fmt ./...
        - name: Run goimports
          run: goimports -w .
        - name: Run golangci-lint
          uses: golangci/golangci-lint-action@v3
          with:
            version: latest